fix init: stopping should succeed if the program is not running

diff --git a/debian/patches/fix_init.patch b/debian/patches/fix_init.patch
--- a/debian/patches/fix_init.patch
+++ b/debian/patches/fix_init.patch
@@ -7,7 +7,7 @@ Index: ejabberd/ejabberd.init.template
 ===================================================================
 --- ejabberd.orig/ejabberd.init.template
 +++ ejabberd/ejabberd.init.template
-@@ -16,9 +16,12 @@
+@@ -16,24 +16,38 @@
  
  set -o errexit
  
@@ -22,10 +22,12 @@ Index: ejabberd/ejabberd.init.template
  
  test -x "$CTL" || {
  	echo "ERROR: ejabberd not found: $DIR"
-@@ -29,11 +32,26 @@ grep ^"$USER": /etc/passwd >/dev/null ||
- 	exit 2
+ 	exit 1
  }
- 
+-grep ^"$USER": /etc/passwd >/dev/null || {
+-	echo "ERROR: System user not found: $USER"
+-	exit 2
++
 +mkrundir()
 +{
 +	if [ ! -d $EJABBERDRUN ]; then
@@ -37,8 +39,8 @@ Index: ejabberd/ejabberd.init.template
 +		chmod 0755 $EJABBERDRUN
 +		chown ejabberd:ejabberd $EJABBERDRUN
 +	fi
-+}
-+
+ }
+ 
 +
  export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
  
@@ -49,6 +51,19 @@ Index: ejabberd/ejabberd.init.template
      echo "Starting ejabberd..."
      su - $USER -c "$CTL start"
      su - $USER -c "$CTL started"
+@@ -42,8 +56,10 @@ case "$1" in
+   stop)
+     test -x "$CTL" || exit 0
+     echo "Stopping ejabberd..."
+-    su - $USER -c "$CTL stop"
+-    su - $USER -c "$CTL stopped"
++    if $CTL status >/dev/null || test $? = 1 ; then
++	    su - $USER -c "$CTL stop"
++	    su - $USER -c "$CTL stopped"
++    fi
+     echo "done."
+     ;;
+   status)
 Index: ejabberd/ejabberdctl.template
 ===================================================================
 --- ejabberd.orig/ejabberdctl.template
