[ejabberd] debian/postinst: enhanced register_admin debian/prerm: added check for running ejabberd before backup debian/ejabberd.cfg: added hostname to admin ACL debian/changelog: Updated

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -77,11 +77,35 @@ root@$HOSTNAME.$DOMAINNAME
 
 register_admin()
 {
-    FLAG="/var/lib/ejabberd/.admin_registered"
-    if [ ! -f $FLAG -a -n "$USER" -a -n "$PASSWD" ]; then
-        sleep 5
-        ejabberdctl register "$USER" "$HOST" "$PASSWD"
-	touch $FLAG
+    if [ -n "$USER" -a -n "$PASSWD" ]; then
+	echo -n "Waiting for ejabberd to register admin user."
+	cnt=0
+	flag=1
+	while ! /usr/sbin/ejabberdctl vhost "$HOST" registered-users >/dev/null ; do
+	    echo -n "."
+	    cnt=`expr $cnt + 1`
+	    if [ $cnt -gt 60 ] ; then
+		echo
+		echo "Can't register admin user \"$USER@$HOST\"."
+		echo -n "Probably ejabberd is configured for serving another hostname."
+		flag=0
+		break
+	    fi
+	    sleep 1
+	done
+
+	echo
+	if [ $flag -eq 1 ] ; then
+	    if ! status=$(/usr/sbin/ejabberdctl register "$USER" "$HOST" "$PASSWD") ; then
+		if echo $status | grep -q "already registered" ; then
+		    echo "Admin user \"$USER@$HOST\" is already registered. Password IS NOT changed."
+		else
+		    echo "Can't register admin user \"$USER@$HOST\"."
+		fi
+	    else
+		echo "Admin user \"$USER@$HOST\" is registered successfully."
+	    fi
+	fi
     fi
 }
 
